### PR TITLE
How do we create a storage interface?

### PR DESCRIPTION
**Pull request by seanmtracey**

### CODE REVIEW

**Comment by railsagainstignorance** [comment]
is there any google documentation that could be linked to?

**Comment by seanmtracey** [comment]
No, we never found the time to document the storage interfaces + the reasons for their existence

**Comment by railsagainstignorance** [comment]
so, dumb question, how do we know this storage interface approach is safe to use?

**Comment by seanmtracey** [comment]
I don't understand your question

**Pull request merged**
